// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFV33kEMx6GxKjJCJSTKRIyIshQYAMU4',
    appId: '1:525754890282:web:919c0f8d10330f8352eb53',
    messagingSenderId: '525754890282',
    projectId: 'laptrinhdidong-9596e',
    authDomain: 'laptrinhdidong-9596e.firebaseapp.com',
    storageBucket: 'laptrinhdidong-9596e.firebasestorage.app',
    measurementId: 'G-G6K63XQYQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIMrAjowZ-TZHrvpY7L5diB6w6XiV_5E',
    appId: '1:525754890282:android:1ce04d8d9e327c2252eb53',
    messagingSenderId: '525754890282',
    projectId: 'laptrinhdidong-9596e',
    storageBucket: 'laptrinhdidong-9596e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKhs4DTguoKb0CCHY7J6XJ8bySAIO49w',
    appId: '1:525754890282:ios:ceb571ebb08f799452eb53',
    messagingSenderId: '525754890282',
    projectId: 'laptrinhdidong-9596e',
    storageBucket: 'laptrinhdidong-9596e.firebasestorage.app',
    iosBundleId: 'com.example.daLaptrinhdidongdetai01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNFV33kEMx6GxKjJCJSTKRIyIshQYAMU4',
    appId: '1:525754890282:web:19e2ae3e7e6dd46752eb53',
    messagingSenderId: '525754890282',
    projectId: 'laptrinhdidong-9596e',
    authDomain: 'laptrinhdidong-9596e.firebaseapp.com',
    storageBucket: 'laptrinhdidong-9596e.firebasestorage.app',
    measurementId: 'G-KBLV4GCS8G',
  );
}
